name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Datalake
    runs-on: ubuntu-latest

    setps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
